[package]
name = "smb-vfs"
description = "Dialect-neutral virtual filesystem interface implemented by storage backends"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
async-trait.workspace = true
smb-proto = { path = "../smb-proto" }
