//! Conformance/interoperability test harness for the smb-rs server.
//!
//! The test *plan* mirrors Microsoft's WindowsProtocolTestSuites FileServer
//! family (MS-SMB2, MS-FSCC, MS-FSA, MS-DFSC, MS-SWN) at the category level.
//! Assertions live here in Rust; the actual SMB traffic is generated by a
//! small Python `smbprotocol` driver (`test/driver/smb_driver.py`) invoked per
//! call. This keeps the tests in idiomatic Rust while reusing a mature client.
//!
//! Two entry points share one case registry:
//! - `cargo test -p smb-testsuite` — interactive, via [`tests/conformance.rs`].
//! - `smb-testrunner` binary — automated, records results under `test/data/`.

use std::collections::BTreeMap;
use std::io::Write;
use std::process::{Command, Stdio};
use std::time::Instant;

use serde::{Deserialize, Serialize};

pub mod cases;
pub mod recorder;

/// Metrics a case may emit (e.g. throughput MB/s), keyed by name.
pub type Metrics = BTreeMap<String, f64>;

/// The SMB server under test.
#[derive(Clone, Debug)]
pub struct Endpoint {
    pub host: String,
    pub port: u16,
    pub user: String,
    pub pass: String,
    pub share: String,
}

impl Endpoint {
    /// Read the endpoint from `SMB_TEST_HOST/PORT/USER/PASS/SHARE`. Returns
    /// `None` when unset so `cargo test` can skip cleanly off a live server.
    pub fn from_env() -> Option<Endpoint> {
        let host = non_empty(std::env::var("SMB_TEST_HOST").ok())?;
        Some(Endpoint {
            host,
            port: std::env::var("SMB_TEST_PORT").ok().and_then(|p| p.parse().ok()).unwrap_or(445),
            user: std::env::var("SMB_TEST_USER").unwrap_or_default(),
            pass: std::env::var("SMB_TEST_PASS").unwrap_or_default(),
            share: std::env::var("SMB_TEST_SHARE").unwrap_or_else(|_| "public".into()),
        })
    }
}

fn non_empty(v: Option<String>) -> Option<String> {
    v.filter(|s| !s.is_empty())
}

/// Per-call connection options (dialect pin, signing, encryption).
#[derive(Default, Clone, Debug)]
pub struct Opts {
    pub sign: bool,
    pub encrypt: bool,
    pub dialect: Option<String>,
}

impl Opts {
    pub fn dialect(d: &str) -> Opts {
        Opts { dialect: Some(d.to_string()), ..Opts::default() }
    }
    pub fn signed() -> Opts {
        Opts { sign: true, ..Opts::default() }
    }
    pub fn encrypted() -> Opts {
        Opts { encrypt: true, ..Opts::default() }
    }
}

/// Locates the Python interpreter and driver script.
#[derive(Clone, Debug)]
pub struct Driver {
    pub python: String,
    pub script: String,
}

impl Driver {
    /// Resolve from `SMB_TEST_PYTHON` / `SMB_TEST_DRIVER`. The driver default
    /// is resolved from the crate location (not the cwd) so it works both from
    /// the workspace root (`smb-testrunner`) and the crate dir (`cargo test`).
    pub fn from_env() -> Driver {
        Driver {
            python: std::env::var("SMB_TEST_PYTHON")
                .unwrap_or_else(|_| "/tmp/smbtest_venv/bin/python".into()),
            script: std::env::var("SMB_TEST_DRIVER").unwrap_or_else(|_| default_driver_script()),
        }
    }
}

/// `<workspace>/test/driver/smb_driver.py`, derived from this crate's path.
fn default_driver_script() -> String {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../test/driver/smb_driver.py")
        .to_string_lossy()
        .into_owned()
}

/// Response from one driver invocation.
#[derive(Deserialize, Debug, Default)]
pub struct DriverResp {
    pub ok: bool,
    #[serde(default)]
    pub error: Option<String>,
    #[serde(default)]
    pub dialect: String,
    #[serde(default)]
    pub steps: Vec<serde_json::Value>,
}

impl DriverResp {
    /// The result JSON of the `idx`-th op, if it ran.
    pub fn step(&self, idx: usize) -> Option<&serde_json::Value> {
        self.steps.get(idx)
    }
}

#[derive(Serialize)]
struct DriverReq<'a> {
    endpoint: EndpointReq<'a>,
    ops: serde_json::Value,
}

#[derive(Serialize)]
struct EndpointReq<'a> {
    host: &'a str,
    port: u16,
    user: &'a str,
    pass: &'a str,
    share: &'a str,
    sign: bool,
    encrypt: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    dialect: Option<&'a str>,
}

/// Context handed to every case: the endpoint plus a way to run SMB ops.
pub struct Ctx<'a> {
    pub ep: &'a Endpoint,
    pub driver: &'a Driver,
}

impl<'a> Ctx<'a> {
    /// Run a sequence of ops against the server with default options.
    pub fn run(&self, ops: serde_json::Value) -> Result<DriverResp, String> {
        self.run_with(&Opts::default(), ops)
    }

    /// Run a sequence of ops with explicit connection options.
    pub fn run_with(&self, opts: &Opts, ops: serde_json::Value) -> Result<DriverResp, String> {
        let req = DriverReq {
            endpoint: EndpointReq {
                host: &self.ep.host,
                port: self.ep.port,
                user: &self.ep.user,
                pass: &self.ep.pass,
                share: &self.ep.share,
                sign: opts.sign,
                encrypt: opts.encrypt,
                dialect: opts.dialect.as_deref(),
            },
            ops,
        };
        let payload = serde_json::to_vec(&req).map_err(|e| e.to_string())?;
        let mut child = Command::new(&self.driver.python)
            .arg(&self.driver.script)
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .map_err(|e| format!("spawn {} failed: {e}", self.driver.python))?;
        child
            .stdin
            .take()
            .ok_or("no stdin")?
            .write_all(&payload)
            .map_err(|e| e.to_string())?;
        let out = child.wait_with_output().map_err(|e| e.to_string())?;
        if !out.status.success() && out.stdout.is_empty() {
            return Err(format!(
                "driver exited {}: {}",
                out.status,
                String::from_utf8_lossy(&out.stderr).trim()
            ));
        }
        serde_json::from_slice(&out.stdout).map_err(|e| {
            format!("bad driver output: {e}: {}", String::from_utf8_lossy(&out.stdout))
        })
    }
}

/// One conformance test case.
pub struct TestCase {
    /// Stable identifier, e.g. `create.overwrite_if`.
    pub id: &'static str,
    /// Grouping used by the runner and UI, e.g. `Create`.
    pub category: &'static str,
    /// Spec / MS-suite reference this mirrors.
    pub spec: &'static str,
    /// One-line description.
    pub about: &'static str,
    /// Runner: `Ok(metrics)` on pass, `Err(message)` on failure.
    pub run: fn(&Ctx) -> Result<Metrics, String>,
}

/// Outcome status for a single case.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum Status {
    Pass,
    Fail,
    Skip,
    Error,
}

/// Recorded result for one case in one run.
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct CaseResult {
    pub id: String,
    pub category: String,
    pub spec: String,
    pub about: String,
    pub status: Status,
    pub duration_ms: u128,
    pub message: String,
    pub metrics: Metrics,
}

/// Execute one case, timing it and converting panics into an `Error` status.
pub fn run_case(case: &TestCase, ctx: &Ctx) -> CaseResult {
    let started = Instant::now();
    let outcome = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| (case.run)(ctx)));
    let duration_ms = started.elapsed().as_millis();
    let (status, message, metrics) = match outcome {
        Ok(Ok(metrics)) => (Status::Pass, String::new(), metrics),
        Ok(Err(msg)) => (Status::Fail, msg, Metrics::new()),
        Err(_) => (Status::Error, "panicked".into(), Metrics::new()),
    };
    CaseResult {
        id: case.id.into(),
        category: case.category.into(),
        spec: case.spec.into(),
        about: case.about.into(),
        status,
        duration_ms,
        message,
        metrics,
    }
}
