[package]
name = "smb-server-proto-smb1"
description = "SMB1 (MS-SMB/MS-CIFS) wire structures: headers, commands, TRANS2 information levels"
edition.workspace = true
version.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
smb-server-proto = { path = "../smb-server-proto", version = "0.2.0" }

[lints]
workspace = true
