[package]
name = "smb-backend-posix"
description = "Default POSIX async-fs storage backend for the smb-server-rs virtual filesystem"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
tokio-uring.workspace = true
xattr.workspace = true
smb-proto = { path = "../smb-proto" }
smb-vfs = { path = "../smb-vfs" }

[lints]
workspace = true
