[package]
name = "smb-server-vfs"
description = "Dialect-neutral virtual filesystem interface implemented by storage backends"
edition.workspace = true
version.workspace = true
license.workspace = true
readme = "README.md"

[dependencies]
thiserror.workspace = true
async-trait.workspace = true
smb-server-proto = { path = "../smb-server-proto" }

[lints]
workspace = true
