[package]
name = "smb-server-vfs"
description = "Dialect-neutral virtual filesystem interface implemented by storage backends"
edition.workspace = true
version.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
thiserror.workspace = true
async-trait.workspace = true
smb-server-proto = { path = "../smb-server-proto", version = "0.2.0" }

[lints]
workspace = true
