[package]
name = "smb-server"
description = "rustsmb — SMB1 file server binary wiring transport, protocol and POSIX backend"
edition.workspace = true
version.workspace = true
license.workspace = true

[[bin]]
name = "rustsmb"
path = "src/main.rs"

[features]
default = ["lib"]
lib = ["smb-auth/lib"]
handrolled = ["smb-auth/handrolled"]

[dependencies]
async-trait.workspace = true
tokio.workspace = true
tokio-uring.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
metrics.workspace = true
metrics-exporter-prometheus.workspace = true
clap.workspace = true
smb-proto = { path = "../smb-proto" }
smb-proto-smb2 = { path = "../smb-proto-smb2" }
smb-proto-smb1 = { path = "../smb-proto-smb1" }
smb-transport = { path = "../smb-transport" }
smb-vfs = { path = "../smb-vfs" }
smb-backend-posix = { path = "../smb-backend-posix" }
smb-auth = { path = "../smb-auth", default-features = false }
smb-handle-store = { path = "../smb-handle-store" }
ms-ndr = "0.1.1"
inotify.workspace = true
futures-util.workspace = true
win-sd.workspace = true
if-addrs.workspace = true
