[package]
name = "smb-server-proto-smb2"
description = "SMB2 wire structures ([MS-SMB2]) — pass 2 scaffold"
edition.workspace = true
version.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
smb-server-proto = { path = "../smb-server-proto", version = "0.2.0" }
smb-server-vfs = { path = "../smb-server-vfs", version = "0.2.0" }
lznt1 = { workspace = true }
xpress_rs = { workspace = true }

[lints]
workspace = true
